### ISSUE TITLE
Requisição de dados não está funcionando. 

### ISSUE THREAD

**Issue by victorhugow** [voltdatalab/pollingBR#4]
Oi, bom dia!

Estou tentando utilizar o pacote, mas parece que tem algum problema.

pollingBR::president(2018)

Extracting data from Poder 360's API of electoral polls.
...

Error: lexical error: invalid char in json text.
                                       <!DOCTYPE html> <!--[if lt IE 7
                     (right here) ------^

Att,
Victor

**Comment by sergiospagnuolo** [comment]
Oi, Victor, a API agora é administrada pelo Poder360 e não damos mais suporte para ela.
